### ISSUE TITLE
Which version of HEAAN I should use?

### ISSUE THREAD

**Issue by yaevk** [kimandrik/IDASH2017#7]
Hello,

When I used `make` in IDASH2017/run, I got this issue:

Building target: IDASH2017
Invoking: MacOS X C++ Linker
g++ -L/home/ruiqi/Documents/HEAAN-master/HEAAN/Debug -L/usr/local/lib -pthread -o "IDASH2017"  ./src/CipherGD.o ./src/GD.o ./src/IDASH2017.o ./src/TestGD.o   -lHEAAN -lntl -lgmp
/usr/bin/ld: cannot find -lHEAAN
collect2: error: ld returned 1 exit status
makefile:45: recipe for target 'IDASH2017' failed
make: *** [IDASH2017] Error 1

I've already checked the makefile, so the problem locates at this block:

```
# Tool invocations
IDASH2017: $(OBJS) $(USER_OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: MacOS X C++ Linker'
	g++ -L/home/ruiqi/Documents/HEAAN-master/HEAAN/Debug -L/usr/local/lib -pthread -o "IDASH2017" $(OBJS) $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' '
```

The HEAAN I installed has no HEAAN/Debug document, it may have caused the problem of make failure. How can I solve this issue?

**Comment by kimandrik** [comment]
Hello, 

Maybe you should use the version from https://github.com/snucrypto/HEAAN. I used eclipse ide, and Debug folder created automatically. In your case, you can use lib folder to generate library and change the paths

**Comment by yaevk** [comment]
It works! Thank you kimandrik!
