### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by nankeep** [kimandrik/IDASH2017#8]
I had installed the HEAAN library and try to "make" in the /lib, but got into some trouble:
  #include <Scheme.h>
          ^~~~~~~~~~
compilation terminated.
src/subdir.mk:27: recipe for target 'src/CipherGD.o' failed
make: *** [src/CipherGD.o] Error 1

please give me some advice. Thanks!

**Comment by kimandrik** [comment]
Maybe you can try make from /run folder. And you should change some paths to yours in makefile, and src/subdir.mk

**Comment by nankeep** [comment]
I change the paths to ../HEAAN/lib/libHEAAN.a, ../HEAAN/src both in /run/makefile and /run/src/subdir.mk .
But the situation has not changed.

**Comment by kimandrik** [comment]
my paths is subdir.mk for src are: 
-I/usr/local/include (ntl and gmp src are there) and  
-I/Users/kimandrik/git/HEAAN/HEAAN/src (HEAAN src is there), can you change these paths to exact paths of yours

**Comment by nankeep** [comment]
I had changed the paths, and it shows  another error:
Can't find -lHEAAN
I try to add PATH, But it's not very effective.
Thank you for your great help!

**Comment by kimandrik** [comment]
Now you have to change the path in Makefile too

**Comment by nankeep** [comment]
Thank you for your guidance.

**Comment by nankeep** [comment]
Sorry to bother you again. It shows"Finished building target: IDASH2017". 
But when I try to "./IDASH2017 "../data/data103x1579.txt" 1 7 5 1 -1 1 5 1". It can only show:
"
data/data103x1579.txt" 1 7 5 1 -1 1 5 1
isYfirst = 1, number of iterations = 7, g_k = 5
factors = 104, samples = 1579, fold = 5
gammaUp = 1, gammaDown = -1, isInitZero = 1
batch = 16, slots = 32768, cnum = 7
------------------
Start Scheme generating...
"
Then kill the program. I installed it in another computer but get the same result.

**Comment by nankeep** [comment]
I've made it. Thanks!
